import { provideNzIcons } from 'ng-zorro-antd/icon'
import {
  AppstoreOutline,
  BellOutline,
  FolderOutline,
  FileTextOutline,
  UsergroupAddOutline,
  ControlOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  SwapOutline,
  UserOutline,
  SettingOutline,
  LogoutOutline,
  UploadOutline,
  DownloadOutline,
  ColumnHeightOutline,
  PercentageOutline,
  ArrowUpOutline,
  ArrowDownOutline,
} from '@ant-design/icons-angular/icons'

export const iconsProvider = provideNzIcons([
  AppstoreOutline,
  BellOutline,
  FolderOutline,
  FileTextOutline,
  UsergroupAddOutline,
  ControlOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  SwapOutline,
  UserOutline,
  SettingOutline,
  LogoutOutline,
  UploadOutline,
  DownloadOutline,
  ColumnHeightOutline,
  PercentageOutline,
  ArrowUpOutline,
  ArrowDownOutline,
])
