export interface UsLcrRow {
  counterparty: string
  keyFactor: string
  lcrWeights: string
  ruleText: string
  notionalPrev: number
  notionalCurr: number
  notionalVar: number
  ncoPrev: number
  ncoCurr: number
  ncoVar: number
}

const empty = (): UsLcrRow => ({
  counterparty: '',
  keyFactor: '',
  lcrWeights: '',
  ruleText: '',
  notionalPrev: 0,
  notionalCurr: 0,
  notionalVar: 0,
  ncoPrev: 0,
  ncoCurr: 0,
  ncoVar: 0,
})

const na = (): UsLcrRow => ({
  ...empty(),
  counterparty: 'N/A',
  keyFactor: 'N/A',
  lcrWeights: 'N/A',
  ruleText: 'N/A',
})

export const US_LCR_DATA_MAP: Record<string, UsLcrRow & { hasAlert?: boolean }> = {
  personal: {
    ...empty(),
    notionalPrev: 22400,
    notionalCurr: 16800,
    notionalVar: 5600,
    ncoPrev: 22400,
    ncoCurr: 16800,
    ncoVar: 5600,
  },
  'personal-demand': {
    ...na(),
    lcrWeights: '3%',
    ruleText: 'N/A',
    notionalPrev: 18500,
    notionalCurr: 18800,
    notionalVar: -300,
    ncoPrev: 18500,
    ncoCurr: 18800,
    ncoVar: -300,
  },
  'personal-cds': {
    ...na(),
    lcrWeights: '10%',
    ruleText: 'N/A',
    notionalPrev: 94200,
    notionalCurr: 93000,
    notionalVar: 1300,
    ncoPrev: 94200,
    ncoCurr: 93000,
    ncoVar: 1300,
  },
  'personal-savings': {
    ...na(),
    lcrWeights: '3%',
    ruleText: 'N/A',
    notionalPrev: 9500,
    notionalCurr: 8700,
    notionalVar: 800,
    ncoPrev: 9500,
    ncoCurr: 8700,
    ncoVar: 800,
  },
  'personal-third': {
    ...na(),
    lcrWeights: '10%',
    ruleText: 'N/A',
    notionalPrev: -5700,
    notionalCurr: -1100,
    notionalVar: -4700,
    ncoPrev: -5700,
    ncoCurr: -1100,
    ncoVar: -4700,
    hasAlert: true,
  },
  'non-personal': {
    ...empty(),
    notionalPrev: 22400,
    notionalCurr: 22400,
    notionalVar: 22400,
    ncoPrev: 22400,
    ncoCurr: 22400,
    ncoVar: 22400,
  },
  'non-personal-sweep': { ...na(), notionalPrev: 18500, notionalCurr: 18500, notionalVar: 18500, ncoPrev: 18500, ncoCurr: 18500, ncoVar: 18500 },
  'non-personal-brokered': { ...na(), notionalPrev: 94200, notionalCurr: 94200, notionalVar: 94200, ncoPrev: 94200, ncoCurr: 94200, ncoVar: 94200 },
  'non-personal-banking': { ...na(), notionalPrev: 9500, notionalCurr: 9500, notionalVar: 9500, ncoPrev: 9500, ncoCurr: 9500, ncoVar: 9500 },
  wholesale: {
    ...empty(),
    notionalPrev: 8800,
    notionalCurr: 8800,
    notionalVar: 8800,
    ncoPrev: 8800,
    ncoCurr: 8800,
    ncoVar: 8800,
  },
  'wholesale-cds': { ...na(), notionalPrev: 22400, notionalCurr: 22400, notionalVar: 22400, ncoPrev: 22400, ncoCurr: 22400, ncoVar: 22400 },
  'wholesale-term': { ...na(), notionalPrev: 18500, notionalCurr: 18500, notionalVar: 18500, ncoPrev: 18500, ncoCurr: 18500, ncoVar: 18500 },
  'wholesale-gtb': {
    ...empty(),
    notionalPrev: 94200,
    notionalCurr: 94200,
    notionalVar: 94200,
    ncoPrev: 94200,
    ncoCurr: 94200,
    ncoVar: 94200,
  },
  'wholesale-gtb-operational': empty(),
  'wholesale-gtb-operational-retail': empty(),
  'wholesale-gtb-operational-retail-insured': {
    ...empty(),
    counterparty: 'Retail/SME',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(3)',
  },
  'wholesale-gtb-operational-retail-uninsured': {
    ...empty(),
    counterparty: 'Retail/SME',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(4)',
  },
  'wholesale-gtb-operational-bank': empty(),
  'wholesale-gtb-operational-bank-insured': {
    ...empty(),
    counterparty: 'Bank',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(3)',
  },
  'wholesale-gtb-operational-bank-uninsured': {
    ...empty(),
    counterparty: 'Bank',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(4)',
  },
  'wholesale-gtb-operational-broker': empty(),
  'wholesale-gtb-operational-broker-insured': {
    ...empty(),
    counterparty: 'Broker Dealers',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(3)',
  },
  'wholesale-gtb-operational-broker-uninsured': {
    ...empty(),
    counterparty: 'Broker Dealers',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(4)',
  },
  'wholesale-gtb-operational-ia': empty(),
  'wholesale-gtb-operational-ia-insured': {
    ...empty(),
    counterparty: 'IA/FMUs/Funds',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(3)',
  },
  'wholesale-gtb-operational-ia-uninsured': {
    ...empty(),
    counterparty: 'IA/FMUs/Funds',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(4)',
  },
  'wholesale-gtb-operational-pension': empty(),
  'wholesale-gtb-operational-pension-insured': {
    ...empty(),
    counterparty: 'Pension Funds',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(3)',
  },
  'wholesale-gtb-operational-pension-uninsured': {
    ...empty(),
    counterparty: 'Pension Funds',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(4)',
  },
  'wholesale-gtb-operational-pse': empty(),
  'wholesale-gtb-operational-pse-insured': {
    ...empty(),
    counterparty: 'PSE/GSE/MDBs',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(3)',
  },
  'wholesale-gtb-operational-pse-uninsured': {
    ...empty(),
    counterparty: 'PSE/GSE/MDBs',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(4)',
  },
  'wholesale-gtb-excess': empty(),
  'wholesale-gtb-excess-retail': empty(),
  'wholesale-gtb-excess-retail-insured': {
    ...empty(),
    counterparty: 'Retail/SME',
    keyFactor: 'Insured',
    lcrWeights: '5%',
    ruleText: '12 CFR 249.32(h)(1)(i)',
  },
  'wholesale-gtb-excess-retail-uninsured': {
    ...empty(),
    counterparty: 'Retail/SME',
    keyFactor: 'Partial or Uninsured',
    lcrWeights: '25%',
    ruleText: '12 CFR 249.32(h)(1)(ii)',
  },
  'wholesale-gtb-excess-bank': {
    ...empty(),
    counterparty: 'Bank',
    keyFactor: '',
    lcrWeights: '100%',
    ruleText: '12 CFR 249.32(h)(2)',
  },
  'wholesale-gtb-excess-broker': {
    ...empty(),
    counterparty: 'Broker Dealers',
    keyFactor: '',
    lcrWeights: '100%',
    ruleText: '12 CFR 249.32(h)(2)',
  },
  'wholesale-gtb-excess-ia': {
    ...empty(),
    counterparty: 'IA/FMUs/Funds',
    keyFactor: '',
    lcrWeights: '100%',
    ruleText: '12 CFR 249.32(h)(2)',
  },
  'wholesale-gtb-excess-pension': {
    ...empty(),
    counterparty: 'Pension Funds',
    keyFactor: '',
    lcrWeights: '40%',
    ruleText: '12 CFR 249.32(h)(1)(ii)',
  },
  'wholesale-gtb-excess-pse': {
    ...empty(),
    counterparty: 'PSE/GSE/MDBs',
    keyFactor: '',
    lcrWeights: '20%',
    ruleText: '12 CFR 249.32(h)(1)(i)',
  },
  'wholesale-gtb-excess-nonfin': {
    ...empty(),
    counterparty: 'Non-Financial Corp',
    keyFactor: '',
    lcrWeights: '40%',
    ruleText: '12 CFR 249.32(h)(1)(ii)',
  },
  pwm: {
    ...empty(),
    notionalPrev: 22400,
    notionalCurr: 16800,
    notionalVar: 5600,
    ncoPrev: 22400,
    ncoCurr: 16800,
    ncoVar: 5600,
  },
  'pwm-cds': {
    ...na(),
    notionalPrev: 18500,
    notionalCurr: 18800,
    notionalVar: -300,
    ncoPrev: 18500,
    ncoCurr: 18800,
    ncoVar: -300,
  },
  'pwm-term': {
    ...na(),
    notionalPrev: 94200,
    notionalCurr: 93000,
    notionalVar: 1300,
    ncoPrev: 94200,
    ncoCurr: 93000,
    ncoVar: 1300,
  },
  'pwm-demand': {
    ...na(),
    notionalPrev: 9500,
    notionalCurr: 8700,
    notionalVar: 800,
    ncoPrev: 9500,
    ncoCurr: 8700,
    ncoVar: 800,
  },
  'pwm-savings': {
    ...na(),
    notionalPrev: -5700,
    notionalCurr: -1100,
    notionalVar: -4700,
    ncoPrev: -5700,
    ncoCurr: -1100,
    ncoVar: -4700,
  },
}
